export const marginMap = {
    'match-silver-Round-8-0': '380px',
    'match-silver-Round-7-1': '280px',
    'match-silver-Round-7-0': '200px',
    'match-silver-Round-6-3': '120px',
    'match-silver-Round-6-2': '120px',
    'match-silver-Round-6-1': '120px',
    'match-silver-Round-6-0': '120px',
    'match-silver-Round-5-4': '60px',
    'match-silver-Round-5-3': '40px',
    'match-silver-Round-5-2': '60px',
    'match-silver-Round-5-1': '60px',
    'match-silver-Round-5-0': '80px',
    'match-silver-Round-4-5': '80px',
    'match-silver-Round-4-3': '100px',
    'match-silver-Round-4-0': '100px',
    'match-silver-Round-1-0': '136px',
    'match-silver-Round-1-6': '68px',
    'match-silver-Round-3-0': '40px',
    'match-silver-Round-3-4': '100px',
    // 'match-Octave-Finals-4': '60px',
    'match-Octave-Finals-5': '60px',
    'match-Round-2-3': '30px',
    'match-Round-2-5': '70px',
    'match-Quarter-Finals-2': '100px',
    'match-Quarter-Finals-3': '120px',
    'match-Quarter-Finals-4': '120px',
    'match-Semi-Finals-0': '60px',
    'match-Semi-Finals-1': '120px'
};

export const connectionsMain = [
  { from: "match-Round-1-0", to: "match-Round-2-0" },
  { from: "match-Round-1-1", to: "match-Round-2-1" },
  { from: "match-Round-1-2", to: "match-Round-2-2" },
  { from: "match-Round-1-3", to: "match-Round-2-3" },
  { from: "match-Round-1-4", to: "match-Round-2-3" },
  { from: "match-Round-1-5", to: "match-Round-2-4" },
  { from: "match-Round-1-6", to: "match-Round-2-5" },
  { from: "match-Round-1-7", to: "match-Round-2-5" },
  { from: "match-Round-1-8", to: "match-Round-2-6" },

  { from: "match-Round-2-0", to: "match-Octave-Finals-0" },
  { from: "match-Round-2-1", to: "match-Octave-Finals-1" },
  { from: "match-Round-2-2", to: "match-Octave-Finals-2" },
  { from: "match-Round-2-3", to: "match-Octave-Finals-3" },
  { from: "match-Round-2-4", to: "match-Octave-Finals-4" },
  { from: "match-Round-2-5", to: "match-Octave-Finals-5" },
  { from: "match-Round-2-6", to: "match-Octave-Finals-6" },
  { from: "match-Round-2-7", to: "match-Octave-Finals-7" },

  { from: "match-Octave-Finals-0", to: "match-Quarter-Finals-0" },
  { from: "match-Octave-Finals-1", to: "match-Quarter-Finals-1" },
  { from: "match-Octave-Finals-2", to: "match-Quarter-Finals-1" },
  { from: "match-Octave-Finals-3", to: "match-Quarter-Finals-2" },
  { from: "match-Octave-Finals-4", to: "match-Quarter-Finals-2" },
  { from: "match-Octave-Finals-5", to: "match-Quarter-Finals-3" },
  { from: "match-Octave-Finals-6", to: "match-Quarter-Finals-3" },

  { from: "match-Quarter-Finals-0", to: "match-Semi-Finals-0" },
  { from: "match-Quarter-Finals-1", to: "match-Semi-Finals-0" },
  { from: "match-Quarter-Finals-2", to: "match-Semi-Finals-1" },
  { from: "match-Quarter-Finals-3", to: "match-Semi-Finals-1" },
];

export const connectionsSilver = [
  { from: "match-silver-Round-1-0", to: "match-silver-Round-2-2" },
  { from: "match-silver-Round-1-1", to: "match-silver-Round-2-3" },
  { from: "match-silver-Round-1-2", to: "match-silver-Round-2-4" },
  { from: "match-silver-Round-1-3", to: "match-silver-Round-2-5" },
  { from: "match-silver-Round-1-4", to: "match-silver-Round-2-6" },
  { from: "match-silver-Round-1-5", to: "match-silver-Round-2-7" },
  { from: "match-silver-Round-1-6", to: "match-silver-Round-2-9" },
  { from: "match-silver-Round-1-7", to: "match-silver-Round-2-10" },
  { from: "match-silver-Round-1-8", to: "match-silver-Round-2-11" },
  { from: "match-silver-Round-1-9", to: "match-silver-Round-2-12" },


  { from: "match-silver-Round-2-0", to: "match-silver-Round-3-0" },
  { from: "match-silver-Round-2-1", to: "match-silver-Round-3-1" },
  { from: "match-silver-Round-2-2", to: "match-silver-Round-3-2" },
  { from: "match-silver-Round-2-3", to: "match-silver-Round-3-2" },
  { from: "match-silver-Round-2-4", to: "match-silver-Round-3-3" },
  { from: "match-silver-Round-2-5", to: "match-silver-Round-3-3" },
  { from: "match-silver-Round-2-6", to: "match-silver-Round-3-4" },
  { from: "match-silver-Round-2-7", to: "match-silver-Round-3-5" },
  { from: "match-silver-Round-2-8", to: "match-silver-Round-3-6" },
  { from: "match-silver-Round-2-9", to: "match-silver-Round-3-7" },
  { from: "match-silver-Round-2-10", to: "match-silver-Round-3-8" },
  { from: "match-silver-Round-2-11", to: "match-silver-Round-3-9" },
  { from: "match-silver-Round-2-12", to: "match-silver-Round-3-10" },
  { from: "match-silver-Round-2-13", to: "match-silver-Round-3-11" },

  { from: "match-silver-Round-3-0", to: "match-silver-Round-4-0" },
  { from: "match-silver-Round-3-1", to: "match-silver-Round-4-0" },
  { from: "match-silver-Round-3-2", to: "match-silver-Round-4-1" },
  { from: "match-silver-Round-3-3", to: "match-silver-Round-4-2" },
  { from: "match-silver-Round-3-4", to: "match-silver-Round-4-3" },
  { from: "match-silver-Round-3-5", to: "match-silver-Round-4-4" },
  { from: "match-silver-Round-3-6", to: "match-silver-Round-4-5" },
  { from: "match-silver-Round-3-7", to: "match-silver-Round-4-5" },
  { from: "match-silver-Round-3-8", to: "match-silver-Round-4-6" },
  { from: "match-silver-Round-3-9", to: "match-silver-Round-4-7" },
  { from: "match-silver-Round-3-10", to: "match-silver-Round-4-8" },

  { from: "match-silver-Round-4-0", to: "match-silver-Round-5-0" },
  { from: "match-silver-Round-4-1", to: "match-silver-Round-5-1" },
  { from: "match-silver-Round-4-2", to: "match-silver-Round-5-1" },
  { from: "match-silver-Round-4-3", to: "match-silver-Round-5-2" },
  { from: "match-silver-Round-4-4", to: "match-silver-Round-5-3" },
  { from: "match-silver-Round-4-5", to: "match-silver-Round-5-4" },
  { from: "match-silver-Round-4-6", to: "match-silver-Round-5-5" },
  { from: "match-silver-Round-4-7", to: "match-silver-Round-5-6" },
  { from: "match-silver-Round-4-8", to: "match-silver-Round-5-7" },

  { from: "match-silver-Round-5-0", to: "match-silver-Round-6-0" },
  { from: "match-silver-Round-5-1", to: "match-silver-Round-6-0" },
  { from: "match-silver-Round-5-2", to: "match-silver-Round-6-1" },
  { from: "match-silver-Round-5-3", to: "match-silver-Round-6-1" },
  { from: "match-silver-Round-5-4", to: "match-silver-Round-6-2" },
  { from: "match-silver-Round-5-5", to: "match-silver-Round-6-2" },
  { from: "match-silver-Round-5-6", to: "match-silver-Round-6-3" },
  { from: "match-silver-Round-5-7", to: "match-silver-Round-6-3" },

  { from: "match-silver-Round-6-0", to: "match-silver-Round-7-0" },
  { from: "match-silver-Round-6-1", to: "match-silver-Round-7-0" },
  { from: "match-silver-Round-6-2", to: "match-silver-Round-7-1" },
  { from: "match-silver-Round-6-3", to: "match-silver-Round-7-1" },

  { from: "match-silver-Round-7-0", to: "match-silver-Round-8-0" },
  { from: "match-silver-Round-7-1", to: "match-silver-Round-8-0" },
]