import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { SubmitForm } from "../components/SubmitForm";



const bodyInfo = {
  game_type: "velit",
  game_code: "ratione",
  game_winner: "ipsa",
  end_turn: 14,
  end_mode: "necessitatibus",
  game_date: "2021-11-17T09:49:22",
  usa_player_id: "qui",
  ussr_player_id: "accusantium",
  video1: "http://www.brown.com/est-aut-aut-dicta-velit-possimus-expedita",
  video2: "http://russel.com/eos-occaecati-culpa-nulla-libero.html",
  video3: "http://www.kunde.com/ut-sunt-velit-hic-necessitatibus",
};

const callAPI = () => {
  fetch("https://tsalpha.klckh.com/api/game-results", {
    method: "POST",
    headers: {
      Accept: "application/json",
      "Content-Type": "application/json",
    },
    body: JSON.stringify(bodyInfo),
  })
    .then((res) => res.json())
    .then((result) => console.log("result", result));
};

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>TS ALPHA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          TWILIGHT STRUGGLE ALPHA SUBMIT FORM
        </h1>
        <SubmitForm />
        <button onClick={callAPI}>Call submit API</button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
